[package]
name = "ldk-lite"
version = "0.1.0"
authors = ["Elias Rohrer <dev@tnull.de>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning = { version = "0.0.110", features = ["max_level_trace", "std"] }
lightning-block-sync = { version = "0.0.110", features = [ "rpc-client" ] }
lightning-invoice = { version = "0.18" }
lightning-net-tokio = { version = "0.0.110" }
lightning-persister = { version = "0.0.110" }
lightning-background-processor = { version = "0.0.110" }
lightning-rapid-gossip-sync = { version = "0.0.110" }

#bdk = "0.20.0"
bdk = { git = "https://github.com/tnull/bdk", branch="feat/use-external-esplora-client", features = ["use-esplora-ureq"]}
bitcoin = "0.28.1"

rand = "0.8.5"
chrono = "0.4"
futures = "0.3"
serde_json = { version = "1.0" }
tokio = { version = "1", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }


[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
